# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='lon',
            field=models.FloatField(),
        ),
    ]
