# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 04:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import GEOSGeometry
from django.db import migrations


def _update_point_field(apps, schema_editor):
    Report = apps.get_model('report', 'Report')
    for r in Report.objects.all():
        r.point = GEOSGeometry('POINT({lon} {lat})'.format(lat=r.lat, lon=r.lon))
        r.save(update_fields=['point'])


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20160901_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='points',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.RunPython(_update_point_field),
    ]
