# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 05:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='points',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, geography=True, null=True, srid=4326),
        ),
    ]
